FROM public.ecr.aws/lambda/python:3.12

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy function code
COPY lambda_function.py ${LAMBDA_TASK_ROOT}
COPY lambdaone ${LAMBDA_TASK_ROOT}/lambdaone
COPY .env.authz ${LAMBDA_TASK_ROOT}/.env

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda_function.handler" ]

# Added to show the port in desktop
EXPOSE 8080